filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/logs/big01_q2.log # <--- This must be the container path
  
  multiline.pattern: '^<log realm='
  multiline.negate: true
  multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]
