version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/config/realm-patterns.yml:/etc/logstash/realm-patterns.yml
    ports:
      - 5044:5044
      - 9600:9600
    depends_on:
      - elasticsearch
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk-network
  
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.2
    container_name: filebeat
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      # Mount the Filebeat config file
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /home/sarvatra.in/jayant.bhadauria/Documents/CBDC/icici-big/modules/big-icici/build/install/big-icici/log/big01_q2.log:/usr/logs/big01_q2.log:ro
      - /home/sarvatra.in/jayant.bhadauria/Documents/CBDC/cbdc-icici/modules/cbdc-icici/build/install/cbdc-icici/log/rtsp_q2.log:/usr/logs/big02_q2.log:ro
      - /home/sarvatra.in/jayant.bhadauria/Documents/CBDC/simulator-service/modules/simulator-service/build/install/simulator-service/log/simulator.log:/usr/logs/big03_q2.log:ro

    depends_on:
      - logstash
    networks:
      - elk-network
    
volumes:
  esdata:

networks:
  elk-network:
    driver: bridge
